package com.android.dialer.smartdial.map;

import android.support.p000v4.util.SimpleArrayMap;
import com.android.dialer.dialpadview.DialpadCharMappings;
import com.google.common.base.Optional;

final class LatinSmartDialMap extends SmartDialMap {
    private static LatinSmartDialMap instance;

    private LatinSmartDialMap() {
    }

    static LatinSmartDialMap getInstance() {
        if (instance == null) {
            instance = new LatinSmartDialMap();
        }
        return instance;
    }

    /* access modifiers changed from: package-private */
    public SimpleArrayMap<Character, Character> getCharToKeyMap() {
        return DialpadCharMappings.getDefaultCharToKeyMap();
    }

    /* access modifiers changed from: package-private */
    public Optional<Character> normalizeCharacter(char c) {
        if (getCharToKeyMap().containsKey(Character.valueOf(c))) {
            return Optional.m67of(Character.valueOf(c));
        }
        switch (c) {
            case 'A':
                return Optional.m67of('a');
            case 'B':
                return Optional.m67of('b');
            case 'C':
                return Optional.m67of('c');
            case 'D':
                return Optional.m67of('d');
            case 'E':
                return Optional.m67of('e');
            case 'F':
                return Optional.m67of('f');
            case 'G':
                return Optional.m67of('g');
            case 'H':
                return Optional.m67of('h');
            case 'I':
                return Optional.m67of('i');
            case 'J':
                return Optional.m67of('j');
            case 'K':
                return Optional.m67of('k');
            case 'L':
                return Optional.m67of('l');
            case 'M':
                return Optional.m67of('m');
            case 'N':
                return Optional.m67of('n');
            case 'O':
                return Optional.m67of('o');
            case 'P':
                return Optional.m67of('p');
            case 'Q':
                return Optional.m67of('q');
            case 'R':
                return Optional.m67of('r');
            case 'S':
                return Optional.m67of('s');
            case 'T':
                return Optional.m67of('t');
            case 'U':
                return Optional.m67of('u');
            case 'V':
                return Optional.m67of('v');
            case 'W':
                return Optional.m67of('w');
            case 'X':
                return Optional.m67of('x');
            case 'Y':
                return Optional.m67of('y');
            case 'Z':
                return Optional.m67of('z');
            case 192:
                return Optional.m67of('a');
            case 193:
                return Optional.m67of('a');
            case 194:
                return Optional.m67of('a');
            case 195:
                return Optional.m67of('a');
            case 196:
                return Optional.m67of('a');
            case 197:
                return Optional.m67of('a');
            case 199:
                return Optional.m67of('c');
            case 200:
                return Optional.m67of('e');
            case 201:
                return Optional.m67of('e');
            case 202:
                return Optional.m67of('e');
            case 203:
                return Optional.m67of('e');
            case 204:
                return Optional.m67of('i');
            case 205:
                return Optional.m67of('i');
            case 206:
                return Optional.m67of('i');
            case 207:
                return Optional.m67of('i');
            case 208:
                return Optional.m67of('d');
            case 209:
                return Optional.m67of('n');
            case 210:
                return Optional.m67of('o');
            case 211:
                return Optional.m67of('o');
            case 212:
                return Optional.m67of('o');
            case 213:
                return Optional.m67of('o');
            case 214:
                return Optional.m67of('o');
            case 215:
                return Optional.m67of('x');
            case 216:
                return Optional.m67of('o');
            case 217:
                return Optional.m67of('u');
            case 218:
                return Optional.m67of('u');
            case 219:
                return Optional.m67of('u');
            case 220:
                return Optional.m67of('u');
            case 221:
                return Optional.m67of('u');
            case 224:
                return Optional.m67of('a');
            case 225:
                return Optional.m67of('a');
            case 226:
                return Optional.m67of('a');
            case 227:
                return Optional.m67of('a');
            case 228:
                return Optional.m67of('a');
            case 229:
                return Optional.m67of('a');
            case 231:
                return Optional.m67of('c');
            case 232:
                return Optional.m67of('e');
            case 233:
                return Optional.m67of('e');
            case 234:
                return Optional.m67of('e');
            case 235:
                return Optional.m67of('e');
            case 236:
                return Optional.m67of('i');
            case 237:
                return Optional.m67of('i');
            case 238:
                return Optional.m67of('i');
            case 239:
                return Optional.m67of('i');
            case 240:
                return Optional.m67of('d');
            case 241:
                return Optional.m67of('n');
            case 242:
                return Optional.m67of('o');
            case 243:
                return Optional.m67of('o');
            case 244:
                return Optional.m67of('o');
            case 245:
                return Optional.m67of('o');
            case 246:
                return Optional.m67of('o');
            case 248:
                return Optional.m67of('o');
            case 249:
                return Optional.m67of('u');
            case 250:
                return Optional.m67of('u');
            case 251:
                return Optional.m67of('u');
            case 252:
                return Optional.m67of('u');
            case 253:
                return Optional.m67of('y');
            case 255:
                return Optional.m67of('y');
            case 256:
                return Optional.m67of('a');
            case 257:
                return Optional.m67of('a');
            case 258:
                return Optional.m67of('a');
            case 259:
                return Optional.m67of('a');
            case 260:
                return Optional.m67of('a');
            case 261:
                return Optional.m67of('a');
            case 262:
                return Optional.m67of('c');
            case 263:
                return Optional.m67of('c');
            case 264:
                return Optional.m67of('c');
            case 265:
                return Optional.m67of('c');
            case 266:
                return Optional.m67of('c');
            case 267:
                return Optional.m67of('c');
            case 268:
                return Optional.m67of('c');
            case 269:
                return Optional.m67of('c');
            case 270:
                return Optional.m67of('d');
            case 271:
                return Optional.m67of('d');
            case 272:
                return Optional.m67of('d');
            case 273:
                return Optional.m67of('d');
            case 274:
                return Optional.m67of('e');
            case 275:
                return Optional.m67of('e');
            case 276:
                return Optional.m67of('e');
            case 277:
                return Optional.m67of('e');
            case 278:
                return Optional.m67of('e');
            case 279:
                return Optional.m67of('e');
            case 280:
                return Optional.m67of('e');
            case 281:
                return Optional.m67of('e');
            case 282:
                return Optional.m67of('e');
            case 283:
                return Optional.m67of('e');
            case 284:
                return Optional.m67of('g');
            case 285:
                return Optional.m67of('g');
            case 286:
                return Optional.m67of('g');
            case 287:
                return Optional.m67of('g');
            case 288:
                return Optional.m67of('g');
            case 289:
                return Optional.m67of('g');
            case 290:
                return Optional.m67of('g');
            case 291:
                return Optional.m67of('g');
            case 292:
                return Optional.m67of('h');
            case 293:
                return Optional.m67of('h');
            case 294:
                return Optional.m67of('h');
            case 295:
                return Optional.m67of('h');
            case 296:
                return Optional.m67of('i');
            case 297:
                return Optional.m67of('i');
            case 298:
                return Optional.m67of('i');
            case 299:
                return Optional.m67of('i');
            case 300:
                return Optional.m67of('i');
            case 301:
                return Optional.m67of('i');
            case 302:
                return Optional.m67of('i');
            case 303:
                return Optional.m67of('i');
            case 304:
                return Optional.m67of('i');
            case 305:
                return Optional.m67of('i');
            case 308:
                return Optional.m67of('j');
            case 309:
                return Optional.m67of('j');
            case 310:
                return Optional.m67of('k');
            case 311:
                return Optional.m67of('k');
            case 312:
                return Optional.m67of('k');
            case 313:
                return Optional.m67of('l');
            case 314:
                return Optional.m67of('l');
            case 315:
                return Optional.m67of('l');
            case 316:
                return Optional.m67of('l');
            case 317:
                return Optional.m67of('l');
            case 318:
                return Optional.m67of('l');
            case 319:
                return Optional.m67of('l');
            case 320:
                return Optional.m67of('l');
            case 321:
                return Optional.m67of('l');
            case 322:
                return Optional.m67of('l');
            case 323:
                return Optional.m67of('n');
            case 324:
                return Optional.m67of('n');
            case 325:
                return Optional.m67of('n');
            case 326:
                return Optional.m67of('n');
            case 327:
                return Optional.m67of('n');
            case 328:
                return Optional.m67of('n');
            case 332:
                return Optional.m67of('o');
            case 333:
                return Optional.m67of('o');
            case 334:
                return Optional.m67of('o');
            case 335:
                return Optional.m67of('o');
            case 336:
                return Optional.m67of('o');
            case 337:
                return Optional.m67of('o');
            case 340:
                return Optional.m67of('r');
            case 341:
                return Optional.m67of('r');
            case 342:
                return Optional.m67of('r');
            case 343:
                return Optional.m67of('r');
            case 344:
                return Optional.m67of('r');
            case 345:
                return Optional.m67of('r');
            case 346:
                return Optional.m67of('s');
            case 347:
                return Optional.m67of('s');
            case 348:
                return Optional.m67of('s');
            case 349:
                return Optional.m67of('s');
            case 350:
                return Optional.m67of('s');
            case 351:
                return Optional.m67of('s');
            case 352:
                return Optional.m67of('s');
            case 353:
                return Optional.m67of('s');
            case 354:
                return Optional.m67of('t');
            case 355:
                return Optional.m67of('t');
            case 356:
                return Optional.m67of('t');
            case 357:
                return Optional.m67of('t');
            case 358:
                return Optional.m67of('t');
            case 359:
                return Optional.m67of('t');
            case 360:
                return Optional.m67of('u');
            case 361:
                return Optional.m67of('u');
            case 362:
                return Optional.m67of('u');
            case 363:
                return Optional.m67of('u');
            case 364:
                return Optional.m67of('u');
            case 365:
                return Optional.m67of('u');
            case 366:
                return Optional.m67of('u');
            case 367:
                return Optional.m67of('u');
            case 368:
                return Optional.m67of('u');
            case 369:
                return Optional.m67of('u');
            case 370:
                return Optional.m67of('u');
            case 371:
                return Optional.m67of('u');
            case 372:
                return Optional.m67of('w');
            case 373:
                return Optional.m67of('w');
            case 374:
                return Optional.m67of('y');
            case 375:
                return Optional.m67of('y');
            case 376:
                return Optional.m67of('y');
            case 377:
                return Optional.m67of('z');
            case 378:
                return Optional.m67of('z');
            case 379:
                return Optional.m67of('z');
            case 380:
                return Optional.m67of('z');
            case 381:
                return Optional.m67of('z');
            case 382:
                return Optional.m67of('z');
            case 383:
                return Optional.m67of('s');
            case 384:
                return Optional.m67of('b');
            case 385:
                return Optional.m67of('b');
            case 386:
                return Optional.m67of('b');
            case 387:
                return Optional.m67of('b');
            case 390:
                return Optional.m67of('o');
            case 391:
                return Optional.m67of('c');
            case 392:
                return Optional.m67of('c');
            case 393:
                return Optional.m67of('d');
            case 394:
                return Optional.m67of('d');
            case 395:
                return Optional.m67of('d');
            case 396:
                return Optional.m67of('d');
            case 397:
                return Optional.m67of('d');
            case 400:
                return Optional.m67of('e');
            case 401:
                return Optional.m67of('f');
            case 402:
                return Optional.m67of('f');
            case 403:
                return Optional.m67of('g');
            case 404:
                return Optional.m67of('g');
            case 406:
                return Optional.m67of('i');
            case 407:
                return Optional.m67of('i');
            case 408:
                return Optional.m67of('k');
            case 409:
                return Optional.m67of('k');
            case 410:
                return Optional.m67of('l');
            case 411:
                return Optional.m67of('l');
            case 412:
                return Optional.m67of('w');
            case 413:
                return Optional.m67of('n');
            case 414:
                return Optional.m67of('n');
            case 415:
                return Optional.m67of('o');
            case 416:
                return Optional.m67of('o');
            case 417:
                return Optional.m67of('o');
            case 420:
                return Optional.m67of('p');
            case 421:
                return Optional.m67of('p');
            case 427:
                return Optional.m67of('t');
            case 428:
                return Optional.m67of('t');
            case 429:
                return Optional.m67of('t');
            case 430:
                return Optional.m67of('t');
            case 431:
                return Optional.m67of('u');
            case 432:
                return Optional.m67of('u');
            case 433:
                return Optional.m67of('y');
            case 434:
                return Optional.m67of('v');
            case 435:
                return Optional.m67of('y');
            case 436:
                return Optional.m67of('y');
            case 437:
                return Optional.m67of('z');
            case 438:
                return Optional.m67of('z');
            case 447:
                return Optional.m67of('w');
            case 461:
                return Optional.m67of('a');
            case 462:
                return Optional.m67of('a');
            case 463:
                return Optional.m67of('i');
            case 464:
                return Optional.m67of('i');
            case 465:
                return Optional.m67of('o');
            case 466:
                return Optional.m67of('o');
            case 467:
                return Optional.m67of('u');
            case 468:
                return Optional.m67of('u');
            case 469:
                return Optional.m67of('u');
            case 470:
                return Optional.m67of('u');
            case 471:
                return Optional.m67of('u');
            case 472:
                return Optional.m67of('u');
            case 473:
                return Optional.m67of('u');
            case 474:
                return Optional.m67of('u');
            case 475:
                return Optional.m67of('u');
            case 476:
                return Optional.m67of('u');
            case 478:
                return Optional.m67of('a');
            case 479:
                return Optional.m67of('a');
            case 480:
                return Optional.m67of('a');
            case 481:
                return Optional.m67of('a');
            case 484:
                return Optional.m67of('g');
            case 485:
                return Optional.m67of('g');
            case 486:
                return Optional.m67of('g');
            case 487:
                return Optional.m67of('g');
            case 488:
                return Optional.m67of('k');
            case 489:
                return Optional.m67of('k');
            case 490:
                return Optional.m67of('o');
            case 491:
                return Optional.m67of('o');
            case 492:
                return Optional.m67of('o');
            case 493:
                return Optional.m67of('o');
            case 496:
                return Optional.m67of('j');
            case 498:
                return Optional.m67of('d');
            case 500:
                return Optional.m67of('g');
            case 501:
                return Optional.m67of('g');
            case 503:
                return Optional.m67of('w');
            case 504:
                return Optional.m67of('n');
            case 505:
                return Optional.m67of('n');
            case 506:
                return Optional.m67of('a');
            case 507:
                return Optional.m67of('a');
            case 510:
                return Optional.m67of('o');
            case 511:
                return Optional.m67of('o');
            case 512:
                return Optional.m67of('a');
            case 513:
                return Optional.m67of('a');
            case 514:
                return Optional.m67of('a');
            case 515:
                return Optional.m67of('a');
            case 516:
                return Optional.m67of('e');
            case 517:
                return Optional.m67of('e');
            case 518:
                return Optional.m67of('e');
            case 519:
                return Optional.m67of('e');
            case 520:
                return Optional.m67of('i');
            case 521:
                return Optional.m67of('i');
            case 522:
                return Optional.m67of('i');
            case 523:
                return Optional.m67of('i');
            case 524:
                return Optional.m67of('o');
            case 525:
                return Optional.m67of('o');
            case 526:
                return Optional.m67of('o');
            case 527:
                return Optional.m67of('o');
            case 528:
                return Optional.m67of('r');
            case 529:
                return Optional.m67of('r');
            case 530:
                return Optional.m67of('r');
            case 531:
                return Optional.m67of('r');
            case 532:
                return Optional.m67of('u');
            case 533:
                return Optional.m67of('u');
            case 534:
                return Optional.m67of('u');
            case 535:
                return Optional.m67of('u');
            case 536:
                return Optional.m67of('s');
            case 537:
                return Optional.m67of('s');
            case 538:
                return Optional.m67of('t');
            case 539:
                return Optional.m67of('t');
            case 540:
                return Optional.m67of('y');
            case 541:
                return Optional.m67of('y');
            case 542:
                return Optional.m67of('h');
            case 543:
                return Optional.m67of('h');
            case 548:
                return Optional.m67of('z');
            case 549:
                return Optional.m67of('z');
            case 550:
                return Optional.m67of('a');
            case 551:
                return Optional.m67of('a');
            case 552:
                return Optional.m67of('e');
            case 553:
                return Optional.m67of('e');
            case 554:
                return Optional.m67of('o');
            case 555:
                return Optional.m67of('o');
            case 556:
                return Optional.m67of('o');
            case 557:
                return Optional.m67of('o');
            case 558:
                return Optional.m67of('o');
            case 559:
                return Optional.m67of('o');
            case 560:
                return Optional.m67of('o');
            case 561:
                return Optional.m67of('o');
            case 562:
                return Optional.m67of('y');
            case 563:
                return Optional.m67of('y');
            default:
                return Optional.absent();
        }
    }
}
